apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: suidex-store
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          clusterLocation: us-east4
          clusterName: gke-suidex-us-east4-cluster
          serviceAccountRef:
            name: external-secret-external-secrets
            namespace: external-secrets
      projectID: suidex
