nameOverride: worker-backend
namespace: suidex-worker-backend


# rollout:
#   annotatelitmus: true


image:
  repository: asia-south1-docker.pkg.dev/suidex/suidex-backend/workers-backend
  tag: fd69c462
configs:
  NODE_ENV: production
  REDIS_URL: redis://redis.redis.svc.cluster.local:6379
  PGSSLMODE: disable
  SUI_RPC_URLS: https://fullnode.mainnet.sui.io:443,https://sui-rpc.publicnode.com
  PRICE_FETCH_CONCURRENCY: 3
  PRICE_RATE_LIMIT_MAX: 500
  VICTORY_TOKEN_ADDRESS: '0xbfac5e1c6bf6ef29b12f7723857695fd2f4da9a11a7d88162c15e9124c243a4a::victory_token::VICTORY_TOKEN' 
  FARM_RATE_LIMIT_MAX: 500
  FARM_CONCURRENCY: 2
  LOCKER_RATE_LIMIT_MAX: 500
  LOCKER_CONCURRENCY: 2
  BLOCK_RATE_LIMIT_MAX: 500
  BLOCK_CONCURRENCY: 2

replicas: 2
resources:
  requests:
    memory: 64Mi
    cpu: 25m
  limits:
    memory: 256Mi
    cpu: 200m
# probes:
#   livenessPath: /internal/alive
#   readinessPath: /internal/ready
#   liveness:
#     initialDelaySeconds: 3
#     periodSeconds: 3
#   readiness:
#     initialDelaySeconds: 5
#     periodSeconds: 5

autoscaling:
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

secrets:
  secretStore: suidex-store
  key: suidex-worker-backend
  data:
    - name: DATABASE_URL
      property: dburl
    - name: NOODLES_API_KEY
      property: noodlekey
    - name: BLOCKBERRY_API_KEY
      property: blockberrykey
    - name: PACKAGE_ID
      property: packageid

ingress:
  enabled: false
  host: suidex-api-backend.suidex.org

prometheus: 
  enabled: false
