argo-cd:
  crds:
    keep: false

  redis-ha:
    enabled: false

  redis:
    enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

  controller:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

  server:
    replicas: 1
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

  repoServer:
    replicas: 1
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

  applicationSet:
    replicas: 1
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi

  dex:
    enabled: true
    resources:
      requests:
        cpu: 5m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi

  notifications:
    enabled: true
    resources:
      requests:
        cpu: 5m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi

